language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

script:
  - ./mvnw clean test -B

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - ./mvnw clean package docker:build -DpushImage -Dproject.version=$TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./target/gitlab-agile-tools.jar
  skip_cleanup: true
  on:
    tags: true