security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: ${ACCESS_TOKEN_URI}
      userAuthorizationUri: ${USER_AUTHORIZATION_URI}
    resource:
      userInfoUri: ${USER_INFO_URI}

spring:
  data:
    mongodb:
      host: app-mongo
      database: AgileTools
      username: agile-tools
      password: ${MONGO_PASSWORD}